name: Update Jaguars Note Content

on:
  schedule:
    # 毎日 6時間おきに自動実行 (UTC時間)
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-blog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests openpyxl

      - name: Run update scripts
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_SCHEDULE_DB_ID: ${{ secrets.NOTION_SCHEDULE_DB_ID }}
          NOTION_NEWS_DB_ID: ${{ secrets.NOTION_NEWS_DB_ID }}
          NOTION_ROSTER_DB_ID: ${{ secrets.NOTION_ROSTER_DB_ID }} # 追加
          HATENA_USER: ${{ secrets.HATENA_USER }}
          HATENA_BLOG: ${{ secrets.HATENA_BLOG }}
          HATENA_API_KEY: ${{ secrets.HATENA_API_KEY }}
          HATENA_SCHEDULE_PAGE_ID: ${{ secrets.HATENA_SCHEDULE_PAGE_ID }}
          HATENA_NEWS_PAGE_ID: ${{ secrets.HATENA_NEWS_PAGE_ID }}
          HATENA_LATEST_NEWS_PAGE_ID: ${{ secrets.HATENA_LATEST_NEWS_PAGE_ID }}
          HATENA_LATEST_SCHEDULE_PAGE_ID: ${{ secrets.HATENA_LATEST_SCHEDULE_PAGE_ID }}
          HATENA_LATEST_ROSTER_PAGE_ID: ${{ secrets.HATENA_LATEST_ROSTER_PAGE_ID }} # 追加
        run: |
          python auto_schedule.py
          python auto_news.py
          python auto_roster.py
